### ISSUE TITLE
Reconcile multiple versions of code

### ISSUE THREAD

**Issue by sfregosi** [sfregosi/CRPTools#1]
combinewhistles and manipulateTonals.m...There are too many versions! Figure out the best/lastest/correct/full versions and update them within this reposiotry

- [x] manipulate tonals
- [x] combine whistles

**Comment by sfregosi** [comment]
Took copious notes and went line by line to compare. 

See combinewhistles notes [here](https://github.com/sfregosi/CRPTools/blob/main/FKW_annotation/combineWhistles_versionIssues/combinewhistles_version_notes.txt)
See manipulateTonals notes [here](https://github.com/sfregosi/CRPTools/tree/main/FKW_annotation/manipulateTonals_versionIssues)

Next step is to actually combine and archive all these old versions.

**Comment by sfregosi** [comment]
@megwood2012 @PinaGruden 
I took a first stab at merging and modifying the manipulate tonals code. I created a new version (eek!) called manipulateTonals.m that is a function with better documentation, and more flexibility with acceptable naming convensions. Megan - this means you shouldn't have to change the way the date/time is extracted between multi-channel or single channel recordings. If there are additional naming conventions in the future, we can add to that flexibility. 

As it stands, this only operates on a single annotation file at a time. From some of @elizabethtaylor1 later versions, she made it so you could loop through a whole folder of .ann files. I did not incorporate that sort of batch processing here because I wanted to keep this function simple. @megwood2012 if you DO want to batch process many .anns, then we can write a script that will call this specific function as you loop through a folder. For my coding preferences, I prefer to have that sort of loop outside of the primary function, but I am open to discuss and modify! 

Because I can't actually get Silbido running on my laptop, I haven't been able to test the full process. I'd like to do this using screensharing at tomorrows meeting, if that is ok with all! 

sf.

**Comment by PinaGruden** [comment]
Thanks Selene,

That sounds great, and I completely agree with your approach- need to keep
these processing steps separate!

Pina

**Comment by sfregosi** [comment]
@megwood2012 the new combineWhistles is a bit more complicated so I will need to test/debug with you. Can we put it on the agenda for Thursday?

**Comment by megwood2012** [comment]
Working on that on Thursday works for me, Selene. Will that be during the regular meeting or would you like to have a separate debug meeting? Let me know!

**Comment by sfregosi** [comment]
Regular meeting! I don't think it should take more than 10-15 minutes. We can do it at the end if Jennifer and Pina want to hop off .

**Comment by sfregosi** [comment]
`combineWhistles` and `silbido_annToCsv` are now both operational and have updated documentation (@megwood2012 you'll want to pull again before using). 
Also note - a new function `dateFromFileName` is required by both of these. This allows flexibility in the naming conventions required to pull "actual time" and can be updated in the future if different filenaming/timestamp conventions are needed.
