### ISSUE TITLE
Check migrated documentation

### ISSUE THREAD

**Issue by sfregosi** [sfregosi/CRPTools#3]

**Comment by sfregosi** [comment]
@megwood2012 I've migrated some of the documentation from Google Drive to GitHub and you can find it in the 'docs' folder here: https://github.com/sfregosi/CRPTools/tree/main/FKW_annotation

Specifically, I formatted the Annotation_Instructions.md. If you [click on that doc through GitHub](https://github.com/sfregosi/CRPTools/blob/main/FKW_annotation/docs/Annotation_Instructions.md) it should look all nicely formatted. 

Could you give it a look on your end and let me know how it is and if I missed anything? 

I did this through R/RStudio using RMarkdown, then rendered it to an .md. That allows for a bit more flexibility than just plain markdown (.md) files, but we can change that if we need. **Do you have R/Rstudio installed?**

**Comment by megwood2012** [comment]
Thanks for all your work on this! I did notice a couple small nitpick things that should be easy to fix. On line 50, 'silbido-init' should actually be 'silbido_init'. Also on line 64 "dtTonalAnnotate('filename', 'file.wav', 'framing', [2 50], 'range', [2000 15000]);" should be "dtTonalAnnotate('Filename', 'file.wav', 'Framing', [2 50], 'Range', [2000 15000]);". I'm not sure if the capitalization actually matters in MatLab, as I've never tried it without the capitals for Filename, Framing, and Range. I don't have R or RStudio downloaded, and haven't actually used either program before, but am willing to learn!

**Comment by sfregosi** [comment]
@megwood2012 thanks for catching these. I've fixed those typos and updated. I also don't know if the capitalization matters :) but better to have what you know works. 

When you get a chance, go ahead and have IT install RStudio and R. No rush on it, but it is good to have and I'm sure at some point we will need to have you run something in R!

**Comment by sfregosi** [comment]
I'm going to 'close' this issue, but if you have anything you want to add in the future, you can create an issue using this tab and then I can make any additional changes. Once you have RStudio working, I can show you how to make the changes directly. 

![image](https://user-images.githubusercontent.com/22456126/200928875-10829d3d-c563-4df1-ad09-1ad2db974420.png)
